name: Linux Remote Desktop

on:
  workflow_dispatch:

jobs:
  linux-rdp:
    runs-on: ubuntu-latest
    timeout-minutes: 3600

    steps:
      - name: Setup Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y xfce4 xrdp firefox-esr

      - name: Create User Account
        run: |
          # Safe password generation
          PASSWORD=$(date +%s | sha256sum | base64 | head -c 12)
          echo "USER_PASSWORD=$PASSWORD" >> $GITHUB_ENV
          
          sudo useradd -m -s /bin/bash linuxuser
          echo "linuxuser:$PASSWORD" | sudo chpasswd
          sudo usermod -a -G sudo linuxuser

      - name: Setup Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscaled --state=mem: &
          sleep 15
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=linux-rdp-$GITHUB_RUN_ID
          echo "TS_IP=$(sudo tailscale ip -4)" >> $GITHUB_ENV

      - name: Start RDP
        run: |
          sudo xrdp-sesman &
          sudo xrdp &
          sleep 3

      - name: Display Info
        run: |
          echo "✅ REMOTE DESKTOP READY"
          echo "========================"
          echo "IP: $TS_IP"
          echo "User: linuxuser"
          echo "Password: $USER_PASSWORD"
          echo "========================"

      - name: Keep Running
        run: |
          while true; do
            sleep 300
            echo "🟢 Active - $(date +%H:%M:%S)"
          done
