name: Simple Ubuntu RDP

on:
  workflow_dispatch:

jobs:
  ubuntu-rdp:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Install XFCE and RDP
        run: |
          sudo apt update
          sudo apt install -y xfce4 xrdp firefox

      - name: Create User
        run: |
          sudo useradd -m -s /bin/bash ubuntuuser
          echo "ubuntuuser:password123" | sudo chpasswd
          sudo usermod -a -G sudo ubuntuuser

      - name: Start RDP
        run: |
          sudo xrdp-sesman &
          sudo xrdp &
          sleep 3
          echo "RDP started on port 3389"

      - name: Show Info
        run: |
          echo "User: ubuntuuser"
          echo "Password: password123"
          echo "Connect via RDP to this machine"

      - name: Keep Running
        run: sleep 3600
